import{a as w,S as v,i as a}from"./assets/vendor-B5nsgUv9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const q="https://pixabay.com/api/",$="54662429-d0583973866d02e67b13f9c1b";async function u(o,r=1){const e={key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};try{return(await w.get(q,{params:e})).data}catch(i){console.log(i),console.log(i.message)}}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),g=document.querySelector(".load"),S=new v(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const r=o.map(e=>`<li class="gallery-item">
              <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" alt="${e.tags}" />
              </a>
              <div class="info">
                <p><b>Likes</b> ${e.likes}</p>
                <p><b>Views</b> ${e.views}</p>
                <p><b>Comments</b> ${e.comments}</p>
                <p><b>Downloads</b> ${e.downloads}</p>
              </div>
            </li>`).join("");f.insertAdjacentHTML("beforeend",r),S.refresh()}function M(){f.innerHTML=""}function y(){p.classList.add("is-visible")}function h(){p.classList.remove("is-visible")}function d(){g.classList.add("is-visible")}function b(){g.classList.remove("is-visible")}b();let l=1;const O=document.querySelector(".form"),n=document.querySelector(".load");let L="";O.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){a.warning({message:"Поле пошуку порожнє!",position:"topRight"});return}L=r,y(),M();try{const e=await u(r,l);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(e.hits),d(),15>e.totalHits?b():d()}catch(e){console.log(e),a.error({message:`something went wrong :( ${e}`,position:"topRight"})}finally{h()}return r});n.addEventListener("click",async()=>{l++,n.disabled=!0,n.innerHTML="Loading...",y();try{const o=await u(L,l);console.log(l),m(o.hits)}catch(o){console.log(o),a.error({message:`something went wrong :( ${o}`,position:"topRight"})}finally{h(),n.disabled=!1,n.innerHTML="Load more"}});
//# sourceMappingURL=index.js.map
