import{a as L,S as w,i as a}from"./assets/vendor-B5nsgUv9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const v="https://pixabay.com/api/",q="54662429-d0583973866d02e67b13f9c1b";async function u(o,r=1){const e={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};try{return(await L.get(v,{params:e})).data}catch(i){console.log(i),console.log(i.message)}}const f=document.querySelector(".gallery"),p=document.querySelector(".loader"),g=document.querySelector(".load"),S=new w(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const r=o.map(e=>`<li class="gallery-item">
              <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" alt="${e.tags}" />
              </a>
              <div class="info">
                <p><b>Likes</b> ${e.likes}</p>
                <p><b>Views</b> ${e.views}</p>
                <p><b>Comments</b> ${e.comments}</p>
                <p><b>Downloads</b> ${e.downloads}</p>
              </div>
            </li>`).join("");f.insertAdjacentHTML("beforeend",r),S.refresh()}function $(){f.innerHTML=""}function y(){p.classList.add("is-visible")}function h(){p.classList.remove("is-visible")}function d(){g.classList.add("is-visible")}function c(){g.classList.remove("is-visible")}c();let n=1;const R=document.querySelector(".form"),O=document.querySelector(".load");let b="";R.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){a.warning({message:"Поле пошуку порожнє!",position:"topRight"});return}n=1,b=r,y(),c(),$();try{const e=await u(r,n);if(e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(e.hits),d(),15>e.totalHits?c():d()}catch(e){console.log(e),a.error({message:`something went wrong :( ${e}`,position:"topRight"})}finally{h()}return r});O.addEventListener("click",async()=>{n++,c(),y();try{const o=await u(b,n);console.log(n),m(o.hits);const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"}),n*15>=o.totalHits?(c(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):d()}catch(o){console.log(o),a.error({message:`something went wrong :( ${o}`,position:"topRight"})}finally{h()}});
//# sourceMappingURL=index.js.map
